### ISSUE TITLE
Not supported response of writable method in ScoreClient

### ISSUE THREAD

**Issue by Suyog007** [icon-project/javaee-annotation-processor#2]
There is an external function with a boolean return type , whenever I try to call that function through the ScoreClient ,an issue is raised that says "Not supported response of writable method in ScoreClient" . However when I call the same function by changing the return type to BigInteger, It did work smoothly.

**Comment by jspark-icon** [comment]
The return value of the writable external method couldn't get via icx_getTransactionResult of JSON-RPC. that's why ScoreClient does not support it.

> However when I call the same function by changing the return type to BigInteger, It did work smoothly.

Which function did you change? generated class or original?

**Comment by ajaya-man** [comment]
```java
@External
boolean distribute();
```

The interface method is defined in this way as it returns data type in the external method. Although the return value can't be obtained during icx_getTransactionResult, the return value can be obtained in inter-score calls. Thus the interface is defined with a return type to match the exact implementation in the contract.

It would be nice to have score-client generate the methods for the above interface method considering it as a void return type. This way the interface would remain the same as the implementation contract and the generated method would also work.

**Comment by ajaya-man** [comment]
Just rechecked the generated file, there is another method that can be used to call these type of external methods.

```java
 /**
   * @deprecated Do not use this method, this is generated only for preventing compile error.
   *  Instead, use distribute(Consumer<TransactionResult> consumerFunc, ...)
   * @throws java.lang.RuntimeException("not supported response of writable method in ScoreClient")
   */
  @Deprecated
  public boolean distribute() {
    throw new RuntimeException("not supported response of writable method in ScoreClient");
  }

  public void distribute(Consumer<TransactionResult> consumerFunc) {
    consumerFunc.accept(super._send("distribute", null));
  }
  ```
