### ISSUE TITLE
Provide configurable block time and result wait time

### ISSUE THREAD

**Issue by ajaya-man** [icon-project/javaee-annotation-processor#5]
It's faster to run integration tests by configuring smaller block time which is possible through the [gochain-local](https://github.com/icon-project/gochain-local/blob/master/data/single/genesis.json#L25) repo. However, the score client is not configurable for a manually configured block time.
https://github.com/icon-project/javaee-annotation-processor/blob/92b3edbc1d8384a591b57097b5960fbd00ee6dce/score-client/src/main/java/foundation/icon/score/client/DefaultScoreClient.java#L57-L58

Thus, it doesn't take advantage of shorter block time in the local environment. It would be better to be able to configure block time in score client too so that score-client can be easily used with the manually configured block time.

**Comment by jspark-icon** [comment]
Implemented in https://github.com/icon-project/javaee-annotation-processor/commit/929c862f16dbfe7d1792885ab8a274577cdf25ab

BLOCK_INTERVAL is removed. Instead, `resultRetryWait * 2` is used and it can be configured by `void _resultRetryWait(long resultRetryWait)`

**Comment by ajaya-man** [comment]
Thanks for the update.
